### PR TITLE
fix highlight bug

### PR DESCRIPTION
**Pull request by asdflj**
fix highlight bug

### CODE REVIEW

**Comment by chochem** [comment]
this doesnt fix anything I am afraid. (and yes I also updated ae2fc to the last jenkins)

**Comment by asdflj** [comment]
@chochem  can you try again?

**Comment by chochem** [comment]
yea give me a moment. Though I dont understand why I have to test your prs in the first place, that should be your job😠

**Comment by asdflj** [comment]
i tried it's look like fine and working

**Comment by asdflj** [comment]
i'm not sure is same working in your game

**Comment by chochem** [comment]
this is affecting everyone, not just me.

and no its still not working.

image


are you really positiv you are testing in 2.2.9 and not just doing dev-env half way testing?

Can we just make a revert for now? then you have all the time in the world to figure this out.

**Comment by asdflj** [comment]
it's same working in the 2.2.9

**Comment by asdflj** [comment]
link https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/243

**Comment by Dream-Master** [comment]
@asdflj are this pr fix the issue now or need it a revert (pr from @chochem) ?

**Comment by asdflj** [comment]
i'm pretty sure woking in my site,but look like not working in other site
@chochem can we just test last one?

**Comment by asdflj** [comment]
use lasted build version

**Comment by Dream-Master** [comment]
@asdflj did you using full 2.2.9 pack ? Or just some dev pack .

**Comment by asdflj** [comment]
i using 2.2.9 pack java 8

**Comment by Dream-Master** [comment]
Are you able to reproduce the bug @chochem mentioned with version before ? @asdflj

**Comment by asdflj** [comment]
it's just a visual error, i can reproduce

**Comment by Dream-Master** [comment]
Ok will tag it and make a version later

**Comment by asdflj** [comment]
thanks

**Comment by chochem** [comment]
updated ae2fs as well, and not this is not a visual thing

**Comment by asdflj** [comment]
strange i'm not change any about interface send item logical
image

**Comment by asdflj** [comment]
image

**Comment by asdflj** [comment]
@chochem  can you provide the save?
@Dream-Master  maybe we can reverse first, and give me sometime let me check my code

**Comment by asdflj** [comment]
@chochem sorry i'm not testing interface part version
now i test part version is working

**Comment by asdflj** [comment]
@Dream-Master can help me rebuild new version?
someone use new verison is working

**Comment by chochem** [comment]
yes, now its working :)

**Comment by Dream-Master** [comment]
if this works we pull this now. A broken version cant be more broken :trollface:

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
