### PR TITLE
rename and prevent NPE

### PR DESCRIPTION
**Pull request by MCTBL**
fixed: [588](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/issues/588)

### CODE REVIEW

**Comment by slprime** [comment]
How to reproduce this bug?

**Comment by MCTBL** [comment]
he siad if there has any thing is acrane recipe will cause this bug, such as Proven Frame.
1. If you order something that use acrane recipe and there has something lacking
2. If you order some acrane thing and lacking some input

then trying click the cancel button with pressing shift.

1. try to order some `Air Crystal Cluster` and `Air Shard` is not enough, then shift click cancel

https://github.com/user-attachments/assets/1722ca88-2b11-4674-9750-4bb55d2fa6ff

2. try to order some `Frame Housing` and some thing is not enough. But there has `Proven Frame` recipe, and shift click cancel

https://github.com/user-attachments/assets/9f7376f8-7c94-4ef9-b049-8e51b1b1aa3e

**Comment by MCTBL** [comment]
this bug is cause by the function that shift click cancel button will add the lacking input into NEI bookmark

**Comment by slprime** [comment]
I get error in another place. it crashed for me because `jobTree` is null. stopped crashed for you after this fix?

**Comment by MCTBL** [comment]
> I get error in another place. it crashed for me because `jobTree` is null. stopped crashed for you after you fix?
> 
> https://mclo.gs/0aTjYBQ

weird, still realted to acrane recipe?

**Comment by MCTBL** [comment]
this is my friend's log

https://mclo.gs/GPhRlzr

**Comment by slprime** [comment]
how looks this gui?
image

**Comment by slprime** [comment]
after you changes bookmarks works fine? (items added?)

**Comment by slprime** [comment]
Please check this branch: https://github.com/slprime/Applied-Energistics-2-Unofficial/tree/fix_nei_bookmarks
I fixed few errors:
1. create output from other property because jobTree can be null
2. create 2 formats of bookmarks. if output item found and without it

P.S. I couldn't reproduce the error with null ingredients
P.S.2. I don't understand how your code doesn't crash with jobTree because the code doesn't know how to restore KnowledgeCore after receiving the tree on the client side

**Comment by MCTBL** [comment]
> after you changes bookmarks works fine? (items added?)

**Pull request closed without merging**
