### PR TITLE
fix black background of "terminal style" gui button

### PR DESCRIPTION
**Pull request by MCTBL**
| before | after |
| :-: | :-: |
| image | image |

### CODE REVIEW

**Comment by MCTBL** [comment]
really thanks for @OneEyeMaker 's help❤

**Comment by Alexdoru** [comment]
why but it outisde of the `if (this.visible)` ? should it be inside of it

**Comment by MCTBL** [comment]
> OpenGlHelper.glBlendFunc(770, 771, 1, 0);

`OpenGlHelper.glBlendFunc(770, 771, 1, 0);` had different logic if use **openGL14**, otherwise will do as same as `GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);`.
not sure this code is necessary?

**Comment by Alexdoru** [comment]
lgtm

**Comment by MCTBL** [comment]
thanks all of you guys

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
