### PR TITLE
Remove Pattern Optimization Matrix requirement from pattern doubling in the interface

### PR DESCRIPTION
**Pull request by kuba6000**

### CODE REVIEW

**Comment by Divran** [comment]
Very cool 👍 

For reference to anyone who doesn't know what this is about, this only affects the new 2x button inside interfaces.

We had a short discussion about this in discord, and most people I saw agree that the new 2x button inside interfaces should be available immediately. Not only I think this, as I said many others agree. See https://discord.com/channels/181078474394566657/401118216228831252/1221194054792908953 for more details

Most people also agree that the auto-multiplication feature should be gated somewhere around mid to late game, and this pr does not change that.

**Review by BlueWeabo — APPROVED** [review]
Fine balance wise

**Comment by Dream-Master** [comment]
ok cool lets merge it

**Comment by Divran** [comment]
> Code-wise PR is OK. I think, that allowing to use part of such QoL feature (automatic pattern multiplication) earlier is good addition.

this pr does not affect automatic multiplication. only the 2x button inside interfaces, which is manual, not automatic. the automatic multiplication still requires a new item called matrix-something (i forget the exact name). which means its only available later.

**Pull request merged**
