### PR TITLE
Add Superluminal Acceleration Card for IOPort

### PR DESCRIPTION
**Pull request by lordIcocain**
1 is 33_554_432 items per operation
2 is 2_148_483_648 items per operation
3 is 137_438_953_472 items per operation
x1000 for fluids.

image

### CODE REVIEW

**Comment by Dream-Master** [comment]
@lordIcocain recipes you are planing after this is merged ?

**Comment by lordIcocain** [comment]
@Dream-Master I havent thought about recipe. I can make tomorrow if you want.

**Comment by Dream-Master** [comment]
if this cards have different tiers i would make look different. Or is this one card have 3 modi ?

**Comment by lordIcocain** [comment]
Its one card. 1,2,3 mean how many cards you put in IO port.

**Comment by EnderProyects** [comment]
image
If you want an idea for a recipe...

**Comment by lordIcocain** [comment]
image
2 tiny chaos fragment
5 hyper speed
1 quantum glass
1 gt++ photon

**Comment by Nockyx** [comment]
image
i think this recipe is more reasonable and also simple enough, being (late uev/early uiv) gated

**Review by S4mpsa — APPROVED** [review]

**Pull request merged**
