### PR TITLE
Feature/hide p2p outputs in interface terminal

### PR DESCRIPTION
**Pull request by hiroscho**
Add a button to toggle p2p output interfaces in the interface terminal. By default p2p output interfaces will be hidden.

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17920

### CODE REVIEW

**Comment by Alexdoru** [comment]
is there really any point showing the interfaces at all ? So you can locate them maybe ?

**Comment by Alexdoru** [comment]
so if I understand correctly the only point of showing the P2P outputs in the terminal is that you can click individually to locate them, other than that all the information is exactly the same across all the interfaces. So I don't really see the point in adding a button to toggle seing P2P

It would be better to change the locate button to highlight all the interfaces that are linked together at once, like it does when you shift click from the crafting gui :
image

**Review by Alexdoru — CHANGES_REQUESTED** [review]
I'm sorry that you made new textures and button but I don't think that's necessary. See my previous comments

**Comment by hiroscho** [comment]
Gonna leave this as a draft for now. I'll probably take a look sometime this week concerning the multilocation highlight.

**Comment by Alexdoru** [comment]
that doesn't work for the AE2FC wireless terminal because as it turns out, the mods is copy pasting the code of AE2 to re-create the interface terminal GUI...

**Pull request closed without merging**
