### PR TITLE
Enable "Use as substitution" by default

### PR DESCRIPTION
**Pull request by miozune**
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11957

### CODE REVIEW

**Comment by chochem** [comment]
Havent looked at the code but in game it does what it says.

However, it might not be that easy. People on discord are reporting that ae2fc things don't work if substitutions are enabled.

**Comment by GlodBlock** [comment]
ae2fc's terminal even doesn't have substitutions button, how they enable it?

**Comment by marcinmagazyn** [comment]
I had issues with most crafting patterns, I just now updated to 2.2.7 from my old 2.2.3, removed the ae2 mod for the one that Chochom linked in the chat (http://jenkins.usrv.eu:8080/job/Applied-Energistics/379/) and most of my issues with ae2 autocrafting went away, the only problems left are with every ae2fc crafting pattern, every normal ae pattern has been fixed.
image
image
image

image
image
image

I'm not sure if what I said was at all relevant to this issue but I was asked to comment here.

**Comment by GlodBlock** [comment]
@marcinmagazyn try this http://jenkins.usrv.eu:8080/job/AE2FluidCraft-Rework/93/

**Comment by marcinmagazyn** [comment]
@GlodBlock just by swapping the mod you linked on my 2.2.7 it changed nothing, let me try to update to 2.2.7 fresh from a new copy of 2.2.3 and report back, I'll add fix for ae and ae2fc and we'll see
image
image
image

**Comment by marcinmagazyn** [comment]
updating from 2.2.3 to 2.2.7, adding 2 fixed mods did nothing for ae2fc and if I look at my old screenshot of 256k drive crfting attempt here, in this issue, I see that additionally, I am missing epoxid bar now, on top od diamond plate and pvc plate 
image
kit as broken as before 
image

Repatterning in ae2fc terminal changes nothing, still can't craft it. 
Nothing I'm trying is making it possible to craft with the ae2fc patterns, I can't make this in any way, not even after making new pattern
image

**Comment by marcinmagazyn** [comment]
I have this book pattern in my system, I just made bookshelf recipe and it is possible to craft it 
image
image
image

**Comment by GlodBlock** [comment]
that bookshelf pattern is a crafting table pattern instead of processing pattern. they are working differently

**Comment by BlueWeabo** [comment]
> that bookshelf pattern is a crafting table pattern instead of processing pattern. they are working differently

It also works as they have the books. it doesn't work if they need to craft them

**Comment by marcinmagazyn** [comment]
> 

Yeah I should've mentioned, I removed the bookshelf post because I had books in the system, I still can't craft with them 
image

**Comment by BlueWeabo** [comment]
By the looks the issue seems to be that AE2FC patterns aren't being recognized as substitute item recipes, which in turn makes them unusable in ae2 patterns that have substitution enabled

**Comment by GlodBlock** [comment]
i tried the same setup in 2.2.7 with the same setup and it works
image
image
image
the normal pattern enables substitute and ae2fc disabled

**Comment by BlueWeabo** [comment]
is the bookshelf enabled to take substitutions? If I know my kanji, it doesn't look like it

**Comment by miozune** [comment]
yeah bookshelf enabling `Using Substitutions` is the key

**Comment by asdflj** [comment]
how to enable substitution in fluid pattern，fluid pattern terminal not even the button

**Review by minecraft7771 — APPROVED** [review]

**Comment by Szajkop** [comment]
i tried to install
- ae2fc-1.7.10-1.0.40-gtnh-1-g649ec0a
- appliedenergistics2-1.7.10-rv3-beta-122-GTNH-2-gd9d92c7

but its not working for me:
image

**Comment by asdflj** [comment]
could you provide the crash report or the client log?

**Pull request merged**
