### PR TITLE
Feature: option to hide "stored" items in ae2 crafting plan

### PR DESCRIPTION
**Pull request by lordIcocain**
https://github.com/user-attachments/assets/de8194a3-f9d7-46a7-b5d8-b0313c162c08

Closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18367

### CODE REVIEW

**Comment by MCTBL** [comment]
should we add  some way to show now is hidding or not hidding?

**Comment by lordIcocain** [comment]
@MCTBL 

https://github.com/user-attachments/assets/e3533330-3e54-4983-9868-257546c70ea6

**Comment by Wo0kiee** [comment]
>  idn.mp4

Maybe it would be a good idea to move the button to the left so they are in the same place.
And make it a texture, so people can change it however they want

**Comment by lordIcocain** [comment]
image
image

**Comment by MCTBL** [comment]
would u think this is better?
| show | hide |
| :-: | :-: |
| image | image |

or change the hide ico to a gray eye?

**Comment by lordIcocain** [comment]
Idk how make reference to dragon ball in button texture, so i don't care how it will look :kekw:

**Comment by bluhbipo** [comment]
finally got around to testing this. the code is currently non functional as it hides some items being crafted but not others
image
image
yes, i double checked with my handy mouse scroll wheel

**Comment by lordIcocain** [comment]
@bluhbipo Should work rn and save able. I also made "terminal style" save able, i think it was bug.

**Comment by bluhbipo** [comment]
feature is fully working!

**Comment by serenibyss** [comment]
Found a minor problem, reproduction case:
1. Start a craft with enough steps and/or stored items to need to scroll to see it all
2. Let it get to a point where there is not enough things to need to scroll when stored items are hidden
3. Hide stored items
4. Close and reopen the UI
5. Show stored items
you can no longer scroll to see everything

**Comment by lordIcocain** [comment]
scroll should updating correct rn

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
