### PR TITLE
change Inscriber recipe match with forming press

### PR DESCRIPTION
**Pull request by Dream-Master**

### CODE REVIEW

**Review by Glease — APPROVED** [review]

**Comment by Serega007RU** [comment]
Why did you change the recipe? not all modpacks have a diamond plate, because of this it is no longer possible to craft the Engineering Processor

**Comment by S4mpsa** [comment]
This version of AE2 is for the GTNH version, so recipe changes that affect other packs aren't exactly a priority. However I agree that maybe the recipe should be done in CoreMod insted of here, although other packs can just modify the recipe themselves.

**Comment by Serega007RU** [comment]
This PR says that this mod supports for use in other modpacks https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/179#pullrequestreview-1119179167

**Comment by glowredman** [comment]
Yeah, the recipes should be in NH-Core, external pack devs are most likely not aware that the recipes changed (speaking from experience...)

**Comment by repo-alt** [comment]
This needs to be rolled back.

**Pull request merged**
