### PR TITLE
Crafting tree view

### PR DESCRIPTION
**Pull request by eigenraven**
- Sets a configurable limit on the number of simulation steps and the size of the serialized tree to prevent DDOS
 - Culls invisible parts of the tree when rendering, tested to maintain high fps on requests with 200k+ individual steps
 - Displays the machines that are responsible for crafting via interfaces, with an API to override the displayed itemstack (for GT hatches to point to their multiblock when implemented)

More features, such as searching, filtering the tree etc. might come in future PRs.

preview screenshot

### CODE REVIEW

**Comment by LewisSaber** [comment]
Can I report bugs? I tried using it and I found 2 bugs
Scroll doesnt work
When ae2 requests some recipe(can be crafting card/level maintainer), gui gets switched to that craft instead of the one u are trying to order

**Comment by eigenraven** [comment]
Read the title, it is very work in progress and most features are not implemented yet. And the recipe tree is read from a static variable for dev until serialization is done.

**Comment by LewisSaber** [comment]
> Read the title, it is very work in progress and most features are not implemented yet. And the recipe tree is read from a static variable for dev until serialization is done.

Sorry for my impatience, but this feature is sooo cool

**Comment by eigenraven** [comment]
Now ready for review.

**Comment by Pilzinsel64** [comment]
Updated on our prod to the `r3-beta-192-GTNH-pre` build just now and we will test this a little bit tomorrow. I'm going to leave a review tomorrow night.

**Review by Pilzinsel64 — APPROVED** [review]

**Pull request merged**
