### PR TITLE
Add crafted item tooltip to the pattern tooltip and craft confirm GUI

### PR DESCRIPTION
**Pull request by repo-alt**
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8187

### CODE REVIEW

**Comment by Glease** [comment]
Maybe a line of text on the GUI saying *Hold shift to view crafted item tooltip*?

**Comment by repo-alt** [comment]
What about pattern item tooltip? It may be displayed in any container

**Comment by repo-alt** [comment]
Technically, this line may be added at the bottom of non-extended tootip...

**Comment by Glease** [comment]
I concern the craft confirm GUI most tbh. Most people press shift to see what's in that pattern, so it's not a concern. However few ever press shift on craft confirm GUI, so chances are that they'd never find out this feature.

**Comment by repo-alt** [comment]
image
didn't find good place for that string on the GUI itself

**Comment by repo-alt** [comment]
(typo in "tooltip")

**Comment by Glease** [comment]
Looks good regardless. I like that.

**Comment by Glease** [comment]
maybe *hold* shift instead of *press*?

**Comment by iouter** [comment]
maybe change a specific key like ctrl or alt. some items have use the shift to show more tooltips.

**Comment by repo-alt** [comment]
> maybe change a specific key like ctrl or alt. some items have use the shift to show more tooltips.

That is ok though? If we hide it by default, then by pressing shift user may want to have all the extended info. Because otherwise he would have to use Alt+Shift which may conflict with e.g. keybord layout switch.

**Comment by repo-alt** [comment]
> maybe hold shift instead of press?

If the user presses and releases the shift he's bound to notice the effect I think, but I'm not native, perhaps "hold" is more clear.

**Comment by iouter** [comment]
> > maybe change a specific key like ctrl or alt. some items have use the shift to show more tooltips.
> 
> That is ok though? If we hide it by default, then by pressing shift user may want to have all the extended info. Because otherwise he would have to use Alt+Shift which may conflict with e.g. keybord layout switch.

ctrl? i know win10 not use ctrl + shift switch the keybord layout.

**Comment by repo-alt** [comment]
image

**Comment by Sphyix** [comment]
shift is used by default with this exact phrasing for "more details" in NEI, so that's the right key to use i think
javaw_oVQaCCN7ji
javaw_9rKI0LbP6t
javaw_5r2RTpH5wK

**Comment by iouter** [comment]
alright. maybe just chinese dont use it.

**Comment by Sphyix** [comment]
repo, is it possible to swap jar client side? and can we get a download for it? ty :P

**Comment by repo-alt** [comment]
[appliedenergistics2-rv3-beta-49-GTNH.jar.zip](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/files/6770837/appliedenergistics2-rv3-beta-49-GTNH.jar.zip)

**Comment by repo-alt** [comment]
[appliedenergistics2-rv3-beta-49-GTNH.jar.zip](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/files/6772385/appliedenergistics2-rv3-beta-49-GTNH.jar.zip)
Updated test build.

**Review by Glease — APPROVED** [review]

**Pull request merged**
