### PR TITLE
Add blue light for drive and ME chest

### PR DESCRIPTION
**Pull request by MCTBL**
3R@ ALY521K}O`XW)I5UJEM

Previously only had three light:
- GREEN for cell which can insert item and new type
- ORANGE for type is full
- RED for bytes  if full

After this will have four light:
- GREEN for total empty cell
- BLUE for cell which can insert item and new type
- ORANGE for type is full
- RED for bytes  if full

this function in higher version AE look like
Cache_-27fadf77b837c5e5

### CODE REVIEW

**Comment by Dream-Master** [comment]
cool idea

**Comment by MCTBL** [comment]
> cool idea

I just back port this feature from newer AE🤠

**Comment by Dream-Master** [comment]
@MCTBL feel free to add more nice stuff from newer version if available.

**Comment by MCTBL** [comment]
Seriously i want to back port this 2, the model will change by which type cell you insert.
image

**Review by OneEyeMaker — APPROVED** [review]

**Pull request merged**
