### PR TITLE
Don't use global state for inventory iteration number

### PR DESCRIPTION
**Pull request by Demiu**
First an in-game scenario

image

Let's call red network main network and green network subnetwork. They are connected by both storage bus and fluid storage bus. Both networks have a discretizer. The tank is there as a stub for a machine

In the main network storage there are liquids. Drops for liquids are visible through crafting terminals on both networks. On the subnetwork in the dual interface there is a crafting recipe which takes in a liquid. Use the crafting interface to start that craft. Now the drop items are only visible through the subnetwork terminal. (Not in the picture) If there is a recipe which takes in a fluid on the main network, trying to start it it will show

image

This is because the droplet inventory of the fluid discretizer on the main network is in a wrong state. Specifically the `itemCache` is empty so `getAvailableItem` which skips the cache and creates the droplet on-demand doesn't match `getAvailableItems` which uses the cache.

The flow of the code is:
* craft issued
* items extracted
* caches invalidated on both networks
* crafting terminal in subnetwork fetches items to display them
  * iteration through subnetwork item inventories (A)
    * subnetwork discretizer droplet inventory is reached
       the cache is null, it fetches the liquid inventory
      * fluid inventory of the subnetwork is iterated through
      * fluid inventory of the main network is iterated through (B)
    * item inventory of the main network is reached
       * main network discretizer droplet inventory is reached
          the cache is null, it fetches the liquid inventory
          * fluid inventory of the main network is iterated through (C)
            this exits early immediately, so the droplet inventory is cached as empty

This happens because `diveIteration` uses static global state `currentPass` for current iteration number:

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/21739d54f0a8fe308037ed125f2374c40138affc/src/main/java/appeng/me/storage/NetworkInventoryHandler.java#L328-L343

Empty `getDepth` return indicates this is a beginning of a new iteration, so a new iteration ID is generated. If `getDepth` is not empty and iteration id of this object matches the global state it means this object was already a part of this iteration. Then in `getAvailableItems`:

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/21739d54f0a8fe308037ed125f2374c40138affc/src/main/java/appeng/me/storage/NetworkInventoryHandler.java#L284-L298

Iteration exits immediately instead of going through the related inventories. The assumption is that whatever this inventory and every inventory in it's list have is already added to `out`

But discretizer is a special case. When rebuilding cache it starts a separate iteration through inventories but on the `FLUIDS` channel. When there are two discretizers there are two separate iterations through `FLUIDS` (B and C) started, but the fluid `out` is not carried over between them, and since all of this is happening in the overall iteration of `ITEMS` (A) whichever iteration happens later will exit early as the fluid inventories have already been checked for the iteration number generated for A

So I've added `int iteration` to `getAvailableItem`/`s` that is passed through the call stack. `getStorageList` and other top-level entrypoints into the `getAvailableItems` stack generate their own non-conflicting iteration IDs with the use of a new helper `IterationCounter.fetchNewId()`

In the real-world scenario discretizer is needed on both networks because without it crafting recipes which output fluids never finish on networks with no discretizer... which I will probably look into later

### CODE REVIEW

**Comment by ReignOfFROZE** [comment]
@Dream-Master I just took a quick glance at this, is the only conflict the IMEInventoryHandler/IMEInventory#getAvailableItems? If so, @Demiu can you add an overload to that method that takes no iteration parameter and either calls the other one with a null or some arbitrary parameter (0, -1, or whatever is most syntactically correct for your code) for that second argument?

**Comment by Demiu** [comment]
@ReignOfFROZE Yes from what I see the only incompatible change is different `getAvailableItems` than the one currently used. I would rather not add an overload taking no iteration number, as it would mean re-introducing of global state

@Dream-Master Since #532 is further along I'm fine with just waiting till it's merged in and rebasing this PR to work with it

I've got changes for (most) repos using AE2 api this changes ready, will make PRs when code review for this is done

**Comment by ReignOfFROZE** [comment]
@Demiu No worries, thanks for that. I'll go ahead and finish up my PR so that you can make the according changes to this PR.

**Comment by Dream-Master** [comment]
@Demiu merge conflict dont solved so it need some fix

**Comment by Demiu** [comment]
I've added a commit fixing build, open and linked PRs to fix dependees after this change

**Comment by OneEyeMaker** [comment]
@Demiu Great job!
This PR really solves the original problem. But after testing, I found another one.
I recreated your setup *exactly* and found that secondary network *visually* duplicates fluid drops.

Fluid stored on disk (main network):


Fluid drops displayed in main network:


Fluid drops displayed in secondary network:


I want to note that both fluid terminals display correct amount. I guess issue caused by combining items from main discretizer through *item* storage bus and secondary one through *fluid* storage bus.

**Comment by Demiu** [comment]
The doubling of the drops is just how it is on master too (before breaking the main net discretizer). It's technically correct-ish - two discretizers see fluids (one of them through fluid bus), both discretize them as drops, terminal sees both discretizer inventories (one of them via storage bus) so the amount of drops is double what it should be, or more, it scales linearly with the amount of discretizers on network (or supernetworks connected with item bus).

I was thinking of fixing that too, but separately. Or at least removing the need for discretizers on connected networks. Right now crafting cpus need discretizers directly on their network or they won't register fluids as being crafted and then they'll get stuck

**Review by OneEyeMaker — APPROVED** [review]

**Comment by eigenraven** [comment]
This needs to be reverted, or methods matching the removed signatures re-added with compatibility wrappers - otherwise this breaks ABI compatibility with older addons we do not have source code for.

**Comment by Demiu** [comment]
@eigenraven I've opened a new PR to address this

**Pull request merged**
