### PR TITLE
Fixed grid pathfinding actually allowing backbone cables to carry more than 32 channels

### PR DESCRIPTION
**Pull request by repo-alt**
also changed/fixed backbone cables connection capabilities to only allow them to connect to dense cables

### CODE REVIEW

**Comment by Glease** [comment]
Are they supposed to be able to go over p2p? It seems to connect to me p2p just fine, but still wouldn't carry more than 32 channels.

**Comment by repo-alt** [comment]
No, they are not supposed to go over p2p, although that may be changed. (Actually, they are not supposed to even connect, but looks like I ovelooked that check)

**Comment by Pilad** [comment]
> also changed/fixed backbone cables connection capabilities to only allow them to connect to dense cables

The ring does not connect to cables. Only for backbone cable. 
Bug?
https://cloud.mail.ru/public/pPRR/a8Z9sEPB6

**Comment by repo-alt** [comment]
Not only backbone, but usual dense cables too. Anyway, not intended.

**Comment by Pilad** [comment]
> Not only backbone, but usual dense cables too. Anyway, not intended.

Connected 3 to 32, but only 64 active 
https://cloud.mail.ru/public/Eimq/YT6TLwt84

**Review by Glease — APPROVED** [review]
Pathfinding seems working now.

------
maybe there is something wrong with smart backbone rendering? this doesn't make a lot of sense to me.

scrn

72 CPU online, with each split off line carrying 18 of them (controller is hidden to the right of the screen). The connection to first junction has all bars lighten up, and the connection from this junction to next one only has 2 bars.

Anyway, it'd be good if you could figure out a way to fix this or explain it, but it probably won't hurt if we just let this in.

**Comment by repo-alt** [comment]
The bars are essentially the same as on usual dense cables just each bar means 16 channels

**Pull request merged**
