### PR TITLE
allow basic expression calulation in craft amount gui

### PR DESCRIPTION
**Pull request by GlodBlock**
image
image
don't ask me why i write this retarded pattern

### CODE REVIEW

**Comment by MuXiu1997** [comment]
https://github.com/fasseg/exp4j
```java
double resultD = new ExpressionBuilder(out).build().evaluate();
```

**Review by eigenraven — CHANGES_REQUESTED** [review]
In ArithHelper.java, what is the point of converting doubles to BigDecimals on every single operations and then immediately converting them back to doubles? Either calculate everything on doubles, or everything on BigDecimals and only convert after the entire expression is evaluated to avoid loss of precision in the middle of computation. I assume this is inspired by <https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6202/files>, why not just use that arithmetic code directly? (might need a couple of tweaks to backport to java 8 but that's it)

**Comment by GlodBlock** [comment]
this pr is actually inspired by the pae2's feature, so i don't notice that arithmetic code in ae2. (i would copy that i knew it existed)
this arithmetic code is copied from my programme homework two years ago. it may contains some shitty code x)

**Comment by MuXiu1997** [comment]
> In ArithHelper.java, what is the point of converting doubles to BigDecimals on every single operations and then immediately converting them back to doubles? Either calculate everything on doubles, or everything on BigDecimals and only convert after the entire expression is evaluated to avoid loss of precision in the middle of computation. I assume this is inspired by https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6202/files, why not just use that arithmetic code directly? (might need a couple of tweaks to backport to java 8 but that's it)

Why repeat the wheel when there are so many mature libs

**Review by repo-alt — APPROVED** [review]
while I kinda agree that writing your own calculator is a bit weird, I don't see how it may be of harm, except some code bloat

**Review by eigenraven — CHANGES_REQUESTED** [review]
The calculator still uses a mix of doubles, Strings and BigDecimals all over the place - can you make ArithHelper and Calculator *only* use BigDecimals, and convert from the String once when parsing input, and format back to a string/double/int once the single final calculated result is ready for display?

**Comment by GlodBlock** [comment]
> The calculator still uses a mix of doubles, Strings and BigDecimals all over the place - can you make ArithHelper and Calculator _only_ use BigDecimals, and convert from the String once when parsing input, and format back to a string/double/int once the single final calculated result is ready for display?

i removed the doubles value in ArithHelper and Calculator. but ArithHelper is using String as input and BigDecimal as output since the stack a mix of operator and numbers so using String will be more easy.

**Comment by GlodBlock** [comment]
well it can be all string in fact

**Review by eigenraven — APPROVED** [review]

**Pull request merged**
