### PR TITLE
Breaking change: Remove ultra dense cables

### PR DESCRIPTION
**Pull request by szuend**
Part of #550 

To keep PR size reasonable for review, I'll remove textures and the ultra dense `AECableType`s separately.

**WARNING**: Existing ultra dense cables will disappear from the world.

### CODE REVIEW

**Comment by serenibyss** [comment]
Why will this crash the client, shouldn't the blocks disappear like normal or is there something I'm missing?

**Comment by szuend** [comment]
All cables use the same block/TileEntity and the cable TE tries to load a part that no longer exists now. I'll do some digging to see whether we can turn this into a more graceful failure or downgrade to dense cables in-place maybe?

**Comment by serenibyss** [comment]
> All cables use the same block/TileEntity and the cable TE tries to load a part that no longer exists now. I'll do some digging to see whether we can turn this into a more graceful failure or downgrade to dense cables in-place maybe?

That would be great, thanks

**Comment by szuend** [comment]
Falling back to dense cables would require us to keep the code around for a version more and implement some kind of migration it seems.

I amended the PR (see b5670a1) to log an error instead. From local testing it seems that ultra dense cables will disappear from the world and the ultra dense cable items will show up as "Disabled item" with the default AE2 "missing item" texture.

**Comment by serenibyss** [comment]
> I amended the PR (see [b5670a1](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/commit/b5670a1b1ccbf7229119e5e58579662730c244db)) to log an error instead. From local testing it seems that ultra dense cables will disappear from the world and the ultra dense cable items will show up as "Disabled item" with the default AE2 "missing item" texture.

This is perfectly good solution, thanks!

**Review by serenibyss — APPROVED** [review]

**Pull request merged**
