### PR TITLE
Add an option to optimize patterns based on crafting plan

### PR DESCRIPTION
**Pull request by kuba6000**
Texture of the block made by @S4mpsa 

1. Adds pattern optimizer to crafting plan screen:
    - Modification is permament
    - Multiplies outputs and inputs by powers of two (up to int max of a single item)
    - Gated by Pattern Optimization Matrix block [(recipe in coremod)](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/806)
    - You can exclude interfaces with a button inside their GUI
    - You can exclude single pattern by clicking on it in the Pattern optimization GUI
    - Each pattern is multiplied based on max steps variable that the user provides. For example
      1. It will take 1000 steps to craft enough x item
      2. user specifies that he wants maximum of 100 steps per item
      3. x item will be multiplied 16 times to satisfy that goal
2. Adds double patterns button to interface
    - Also gated by Pattern Optimization Matrix block
3. Add an option do divide patterns by right click on double pattern(s) buttons

image
image
image

image
image
image

Default recipe
image

### CODE REVIEW

**Comment by Alastors** [comment]
This texture isn’t the final, right?

**Comment by kuba6000** [comment]
> This texture isn’t the final, right?

ye, it's not final

**Comment by Divran** [comment]
imo it would be better if this was just a button on each interface instead because the way this works doesn't seem to allow multiplying recipes in different interfaces by different amounts.

or both? both is good

**Comment by kuba6000** [comment]
> imo it would be better if this was just a button on each interface instead because the way this works doesn't seem to allow multiplying recipes in different interfaces by different amounts.
> 
> or both? both is good

I can also add a button to the interface, but I think that optimizing patterns based on crafting plan is better because you dont have to go into each interface and multiply them. Also patterns are multiplied less when its not needed that much.

**Comment by Divran** [comment]
> > imo it would be better if this was just a button on each interface instead because the way this works doesn't seem to allow multiplying recipes in different interfaces by different amounts.
> > or both? both is good
> 
> I can also add a button to the interface, but I think that optimizing patterns based on crafting plan is better because you dont have to go into each interface and multiply them. Also patterns are multiplied less when its not needed that much.

Biggest issue with multiplying all recipes is if it's not in a crib or equally "infinitely" large storage, it will slow down ae insert speed if it's multiplied to be larger than the size of the bus or hatch. 

So the solution then is to disable the option on that interface, right? But what if you still want to multiply the recipes in that interface up to the size of the bus or hatch?

I've suggested a very similar feature to this in the past, the difference being I wanted to put the option as a button on each interface, and I wanted the user to input the size of the hatch/bus and have all recipes be multiplied up to that amount. May need two text boxes tho, one for the bus and another for the hatch. But this feature might be overkill. 

In fact the button could be as simple as click to 2x, ctrl click to /2. Or maybe ctrl click to 8x so it matches the existing 2x button and then shift click to /2, and ctrl+shift to /8

If this would cause one or more recipes to become larger than the input, the user could either divide it back down to undo it or they could manually adjust that one specific recipe after. 

Could also add this shift click to the existing 2x button as well

**Comment by Divran** [comment]
Excellent

**Comment by LewisSaber** [comment]
image

I suggest rewriting this text to something like
Option unavailable: 
No Pattern Optimization matrix in network

Its far too long and looks ugly

**Comment by kuba6000** [comment]
> image
> 
> I suggest rewriting this text to something like Option unavailable: No Pattern Optimization matrix in network
> 
> Its far too long and looks ugly

image
I made it wrapped, just need to fix the colors

**Comment by AbdielKavash** [comment]
This might be a weird question, but can it optimize pattern sizes *down*? For example, pattern takes 800 inputs and makes 800 outputs, the craft needs 10 of this, can you reduce the pattern down to 100-100 or 50-50 or some closer number?

**Comment by kuba6000** [comment]
> This might be a weird question, but can it optimize pattern sizes _down_? For example, pattern takes 800 inputs and makes 800 outputs, the craft needs 10 of this, can you reduce the pattern down to 100-100 or 50-50 or some closer number?

No, I can add a switch to do that but I dont know if thats a good idea. What if you had already some input in your system and it got requested once. It will potentially shrink the pattern unwantedly.

**Comment by MCTBL** [comment]
some time right click the double parrtens button won't divide the number but double it, also with shift right click.(Not very frequent)
image

image

**Comment by MCTBL** [comment]
only use right click and shift

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/eb8aecee-320a-4f61-bf37-36920bdcd1fb

**Comment by miaowwwwww** [comment]
if haven't, plz add support to the rest 3 items that can hold patterns. "dual-interface", "item crib", "item&fluid crib"

**Review by Laiff — APPROVED** [review]

**Pull request merged**
