### PR TITLE
Profiling command

### PR DESCRIPTION
**Pull request by repo-alt**
To enable call "/ae2 profile x y z" passing coordinates of some tile in the AE grid (e.g. controller). 
Run again to stop. Sampling array is 200 ticks long, then it loops over. Result is average nanoseconds per tick.
image

### CODE REVIEW

**Comment by boubou19** [comment]
the command is op level 4, can you get it to 2? so that way any operator will be able to use it.

**Comment by Glease** [comment]
Preferably also a way to specify dim id instead of taking the command sender's world, so it would be more convenient to issue from server console.

**Comment by bombcar** [comment]
Could/would it make sense for Opis to be able to call this

**Review by Glease — COMMENTED** [review]
Opis support can wait. Let's get the base feature in first.

**Review by Glease — APPROVED** [review]

**Pull request merged**
