### PR TITLE
Feature/item storage bus export filter

### PR DESCRIPTION
**Pull request by hiroscho**
Enables an item storage bus to only show filtered items and only allow the extraction of the filtered items.

Right now it uses the existing input partition list to determine the filtered items. 
To keep existing behavior the extraction filter is only active when access is set to read. This trigger could be replaced with a new setting or a new card.

### CODE REVIEW

**Comment by hiroscho** [comment]
While looking at the `PartFluidStorageBus` I noticed that it handles inject-only buses so that they don't post changes to their network. Since something similar is done when changes are discarded by the extract filter this behavior is now also active on inject-only item storage buses.

**Comment by MCTBL** [comment]
other seems pretty good

**Review by Laiff — APPROVED** [review]

**Comment by MCTBL** [comment]
image
image
Inverter Card can't working correctly

**Comment by AnrDaemon** [comment]
Why not use view cells to filter what could be visible through storage bus??

**Comment by FourIsTheNumber** [comment]
> Why not use view cells to filter what could be visible through storage bus??

For automation, of course?

**Comment by hiroscho** [comment]
> Why not use view cells to filter what could be visible through storage bus??

You could do that but it would make the extract filter function more annoying to use. Instead of just adding the items/fluids you want to see in the subnet you'd need to partition a view cell and add it into the storage bus.
Also storage bus partitions should be large enough with capacity cards, if not just add another storage bus.

**Comment by AnrDaemon** [comment]
Fair point. And you can't copy view cell with memory card?

**Pull request merged**
