### PR TITLE
Revert Shift To Freeze

### PR DESCRIPTION
**Pull request by Caedis**
Reverting these for now due to issues with the implementation

https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/188 will also need to be reverted

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16098
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16093

### CODE REVIEW

**Comment by Caedis** [comment]
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16098

**Comment by Dream-Master** [comment]
@Caedis can we not wrote a fix instead of revert it ?

**Comment by boubou19** [comment]
tbh the feature is hardly interesting, and it causes too many issues on gigantic networks. The more you have items in your network, the more it'll lag.On the original PR, the author tests on a very small storage, so it works well.

**Comment by chochem** [comment]
probably also fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16093?

**Comment by chochem** [comment]
> @Caedis can we not wrote a fix instead of revert it ?

nobody has been able to fix it for 4 months. its a right mess.

**Comment by Caedis** [comment]
Before this is merged, can someone check it in game? I dont have a save setup for it

**Comment by boubou19** [comment]
tested this PR, it totally removed the issue, it's playable again for me.

**Review by boubou19 — APPROVED** [review]

**Pull request merged**
