### PR TITLE
p2p interface config copy paste

### PR DESCRIPTION
**Pull request by LewisSaber**
Config includes: blocking mode, insertion mode, visibility in interface terminal and adv blocking card setting
Any feedback is appreciated, I tried my best at digging in ae2 code
After this gets approved/merged I will do simmilar thing to dual interface p2p in AE2FC

### CODE REVIEW

**Comment by LewisSaber** [comment]
Why does it fail to build

**Comment by Dream-Master** [comment]
@LewisSaber but it works in pre tag or build

**Comment by Dream-Master** [comment]
magic it works now

**Comment by LewisSaber** [comment]
I like this kind of magik fr

**Review by Laiff — APPROVED** [review]

**Pull request merged**
