### PR TITLE
Hyper speed for Import/export Bus.

### PR DESCRIPTION
**Pull request by Pilad**
Add hyper speed upgrade to Import/export bus.

### CODE REVIEW

**Comment by chochem** [comment]
pretty sure thats just meant for the io port

**Comment by King65868** [comment]
It’s used for the fluid Import/export buses too

**Comment by chochem** [comment]
looks like other devs are fine with it. Though it still doesn't have a proper recipe of course.

**Comment by chochem** [comment]
you still got to spotlessappy :P

**Comment by firenoo** [comment]
FYI this PR doesn't actually make the upgrade do anything atm, need to change PartSharedImportBus behavior too iirc

**Comment by Pilad** [comment]
I agree, it still needs to be added to PartSharedItemBus.

**Comment by firenoo** [comment]
Do you have a proposal for balancing?

**Comment by Pilad** [comment]
I'm not a developer, let DreamMaster and others decide what's right for them. And fix the code.

**Comment by firenoo** [comment]
In that case please change this to draft/DNM. It'd be problematic if it was added and we started getting bug reports about unimplemented functionality

**Comment by boubou19** [comment]
@Pilad any news on this?

**Pull request closed without merging**
