### PR TITLE
Add Singularity Crafting Storage

### PR DESCRIPTION
**Pull request by lordIcocain**
On endgame you need huge crafting storage, to get enough bytes need build giant crafting CPU, that pretty laggy, this might help.
image
image
image
image

### CODE REVIEW

**Comment by SMSum** [comment]
I havent done a full deep dive into AE2 but last time I did, the craftter storage cells do store NBT data. Its an arrayList of the itemStacks its holding, ALL the interfaces used for the craft including patterns + coordinates, the crafting tasks at hand and a few other things. I think the biggest concern I'd have with a singularity storage block for crafters is accidentally corrupting a chunk from NBT overload on world save.

**Comment by vovaksenov** [comment]
I dont think the recipe fits the pack. How about a more involved one like in assline?

**Comment by EnderProyects** [comment]
Or in the space assembler

**Comment by EnderProyects** [comment]
image
Something like this? the blocks being the fluids ( titanium, Infi, cosmic neutronium, americium)

**Comment by LewisSaber** [comment]
> image Something like this? the blocks being the fluids ( titanium, Infi, cosmic neutronium, americium)

I would add empty crafting unit and some pico circuits

**Comment by EnderProyects** [comment]
The materials of the craftring unit are in there, but splited in the titanium plates and circuits

**Comment by EnderProyects** [comment]
image
Added some kind of fluix, like fluix pearls, and certus plates, as well as the pico circuits

**Comment by Dream-Master** [comment]
Why the recipe use a pick circuit but only titanium plates. Better choose high tier materials.

**Comment by vovaksenov** [comment]
I would suggest considering the following:
- instead of using metal plates in the recipe use frameboxes, and put them in the 1st slot so it looks in line with other recipes (as if you are "filling" the frame boxes).
- titanium fits the recipe because it is a primary AE material. If it has to be changed, titanium-based materials like astral titanium or one of the nitinols can be considered.
- fluix pearls look out of place, as the ccpu has nothing to do with wireless ae, use singularities instead (or any other fitting placeholder item).
- i personally would also rearrange some other parts, like putting pico circuits into 2nd slot (or before the ME circuits) and moving the quartz plates to the last one. Iirc the order does not matter in this case functionally, but it would look more aesthetically pleasing in NEI imo..

**Comment by lordIcocain** [comment]
What you think about these?
- Other ME "Creative" stuff require Dire for crafting, i don't think that we need change that pattern
- Contain Shirabon/SpaceTime, every good thing gated with that materials
- Contain annoying materials that never used before and never used after


image

4 Neutronium Energy Cell
8 Quantum circuit
12 UMV filed generator
8 Reactor Stabilizer 
4 Instability Orb 
24 Dense Shirabon Plate
12 16x SpaceTime Wire
8 ME Digital singularitie
1 crafting unit

**Comment by Hikari1nVoid** [comment]
Disasterous recipe.Unless it can handle 2,147,483,647 different tasks at the same time.

**Comment by Dream-Master** [comment]
> Disasterous recipe.Unless it can handle 2,147,483,647 different tasks at the same time. ALso plz kick HEE stuff out of the recipe.

replace with Stargate components :trollface:

**Comment by lordIcocain** [comment]
> Disasterous recipe.Unless it can handle 2,147,483,647 different tasks at the same time. ALso plz kick HEE stuff out of the recipe.

Why kick HEE? its just rare ore from end, you can get it just flying around or call meteor, not a big deal. Anyway you need kill chaos dragon for this recipe, so why not HEE material ^)

**Comment by Hikari1nVoid** [comment]
> > Disasterous recipe.Unless it can handle 2,147,483,647 different tasks at the same time. ALso plz kick HEE stuff out of the recipe.
> 
> replace with Stargate components :trollface:

better than these ridicilous instability orbs.

**Comment by EnderProyects** [comment]
Change the orbs with ae singularity' s and then you have it

**Comment by lordIcocain** [comment]
okay, what if replace this perfect instability orbs with this one
image

**Comment by bombcar** [comment]
> okay, what if replace this perfect instability orbs with this one image

eeek I'd stay away from bad graphics ghosts from gt++ in general

**Comment by Laiff** [comment]
I fine with item like this, but recipe shouldn't be gated to far away from it real necessarily. I propose to continue discussion in separate PR in CoreMod. From my point of view it should be slightly harder than `ME Fluid Digital Singularity Storage Cell`

**Review by Laiff — APPROVED** [review]

**Comment by Dream-Master** [comment]
@lordIcocain the recipe be added in core mod ?

**Comment by lordIcocain** [comment]
@Dream-Master yeah, i will make pr

**Pull request merged**
