### PR TITLE
Add API to get power state text

### PR DESCRIPTION
**Pull request by miozune**

### CODE REVIEW

**Comment by firenoo** [comment]
Use case?

**Review by OneEyeMaker — APPROVED** [review]

**Comment by Dream-Master** [comment]
@miozune

**Comment by firenoo** [comment]
We can merge, just want to document the change before the reason is forgotten for whatever reason

**Review by firenoo — APPROVED** [review]

**Comment by miozune** [comment]
I want to use it for displaying network status on stocking bus GUI

**Pull request merged**
